{
    'name': 'Numa FSM',
    'version': '18.0.1.0.0',
    'summary': 'Finite State Machine engine for process automation.',
    'author': 'NUMA Extreme Systems',
    'website': 'https://www.numaes.com',
    'license': 'LGPL-3',
    'category': 'Extra Tools',
    'depends': [
        'base',
        'mail',
        'numa_poly',
        'website',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/fsm_views.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'numa_fsm/static/src/components/fsm_diagram/fsm_diagram.scss',
            'numa_fsm/static/src/components/fsm_diagram/fsm_node.scss',
            'numa_fsm/static/src/components/fsm_diagram/fsm_transition_editor.scss',
            'numa_fsm/static/src/components/fsm_diagram/fsm_state_editor.scss',
            'numa_fsm/static/src/components/fsm_diagram/fsm_node_creator.scss',
            'numa_fsm/static/src/components/fsm_diagram/fsm_diagram.js',
            'numa_fsm/static/src/components/fsm_diagram/fsm_node.js',
            'numa_fsm/static/src/components/fsm_diagram/fsm_transition_editor.js',
            'numa_fsm/static/src/components/fsm_diagram/fsm_state_editor.js',
            'numa_fsm/static/src/components/fsm_diagram/fsm_node_creator.js',
            'numa_fsm/static/src/xml/fsm_diagram.xml',
            'numa_fsm/static/src/xml/fsm_node.xml',
            'numa_fsm/static/src/xml/fsm_transition_editor.xml',
            'numa_fsm/static/src/xml/fsm_state_editor.xml',
            'numa_fsm/static/src/xml/fsm_node_creator.xml',
        ],
    },
    'installable': True,
}
