from . import test_numa_product_variant
from . import test_purchase_configurator
from . import test_purchase_configurator_controllers
from . import test_attribute_typing
from . import test_materialization
from . import test_codes
from . import test_lifecycle
from . import test_resolution_api
from . import test_resolve_value_controllers
